# Generated by Django 6.0.1 on 2026-01-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='desription',
            new_name='desсription',
        ),
    ]
