# Generated by Django 6.0.1 on 2026-01-10 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_desription_item_desсription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='desсription',
            new_name='description',
        ),
    ]
