# Generated by Django 6.0.1 on 2026-01-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_order_alter_item_price_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='snapshot_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
