# Generated by Django 6.0.1 on 2026-01-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_orderitem_snapshot_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='snapshot_price',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
