# Generated by Django 6.0.1 on 2026-01-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_orderitem_snapshot_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stripe_coupon_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stripe_tax_rate_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ManyToManyField(to='product.discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ManyToManyField(to='product.tax'),
        ),
    ]
