# Generated by Django 6.0.1 on 2026-01-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_discount_tax_order_discount_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.ManyToManyField(to='product.discount'),
        ),
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ManyToManyField(to='product.tax'),
        ),
    ]
