# Generated by Django 6.0.1 on 2026-01-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_item_discount_item_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'Taxes'},
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.ManyToManyField(blank=True, to='product.discount'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tax',
            field=models.ManyToManyField(blank=True, to='product.tax'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ManyToManyField(blank=True, to='product.discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.ManyToManyField(blank=True, to='product.tax'),
        ),
    ]
