# Generated by Django 6.0.1 on 2026-01-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
